fix: nil pointer when evaluating when cronjob.enabled=true
The `if` block checking if Redis is enabled needs to be anchored
correctly since we are inside a `with` block (`with
.Values.cronjob.sidecar`). Otherwise you get an error:

```
Error: nextcloud/templates/deployment.yaml:274:26
  executing "nextcloud/templates/deployment.yaml" at <.Values.redis.enabled>:
    nil pointer evaluating interface {}.redis
```

Signed-off-by: sapslaj <saps.laj@gmail.com>